# Generated by Django 2.1.2 on 2018-12-18 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='finger_printe',
            field=models.TextField(validators=[django.core.validators.int_list_validator]),
        ),
    ]
